In [48]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [49]:
df = pd.read_csv('insurance.csv')
df.head(5)

age  affordability  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [50]:
df.shape

(28, 3)

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordability']], df.bought_insurance, test_size=0.2, random_state=25)

In [52]:
len(X_train)

22

In [53]:
X_train

age  affordability
0    22              1
13   29              0
6    55              0
17   58              1
24   50              1
19   18              1
25   54              1
16   25              0
20   21              1
3    52              0
7    60              0
1    25              0
5    56              1
27   22              1
8    62              1
18   19              0
12   27              0
23   45              1
22   40              1
15   55              1
26   23              1
4    46              1

In [54]:
df.shape

(28, 3)

In [55]:
## SCALING; simply divide by 100, since the age is between 1 to 100

In [56]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [57]:
X_train_scaled

age  affordability
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.22              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

## Building a simple neural network

In [58]:
##1 reps the number of outputs(i.e, y).  while input_shape means the number of inputs, then the loss binary crossentropy is the same as logloss
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=5000)

Epoch 1/5000


c:\Users\HomePC\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.7027
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5000 - loss: 0.7023
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.5000 - loss: 0.7020
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.5000 - loss: 0.7016
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.5000 - loss: 0.7012
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.5000 - loss: 0.7009
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5000 - loss: 0.7005
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5000 - loss: 0.7001
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5000 - loss: 0.6998
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.5000 - loss: 0.6994
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.5000 - loss: 0.6991
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.5000 - 

In [59]:
##Evaluating the model

model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 351ms/step - accuracy: 1.0000 - loss: 0.3432


[0.3431582450866699, 1.0]

In [60]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step


array([[0.73326576],
       [0.36175713],
       [0.16386652],
       [0.49418464],
       [0.75401694],
       [0.8548963 ]], dtype=float32)

In [61]:
X_test_scaled

age  affordability
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [62]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [63]:
coef, intercept = model.get_weights()

In [64]:
coef, intercept

(array([[5.4448314],
        [1.497577 ]], dtype=float32),
 array([-3.0453923], dtype=float32))

In [65]:
def sigmoid(x):
        import numpy as np
        return 1 / (1 + np.exp(-x))
sigmoid(18)

np.float64(0.9999999847700205)

## Neural network without TensorFlow

In [66]:

def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

prediction_function(0.47, 1.0)

array([0.7332658], dtype=float32)

In [67]:
prediction_function(0.18, 1.0)

array([0.36175716], dtype=float32)

In [68]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [69]:

def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [70]:
def gradient_descent(age, affordability, y_true, epochs):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)

        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

    return w1, w2, bias

In [71]:

gradient_descent(X_train_scaled['age'],X_train_scaled['affordability'],y_train,1000)

Epoch:0, w1:0.9795315209594441, w2:0.9492451509708789, bias:-0.11252165178733592, loss:0.7026974954757434
Epoch:1, w1:0.9645976725710581, w2:0.9075461514920868, bias:-0.2106906494479398, loss:0.6735456568147277
Epoch:2, w1:0.9547110050786667, w2:0.8742482165151655, bias:-0.29581941661734007, loss:0.6520372261076537
Epoch:3, w1:0.9492998511652697, w2:0.8484835924684363, bias:-0.3694132143012605, loss:0.6363983632285396
Epoch:4, w1:0.9477681190800475, w2:0.8292893292838077, bias:-0.4330203349934106, loss:0.6251004827815608
Epoch:5, w1:0.9495395977826652, w2:0.8156998101423668, bias:-0.48812360294921553, loss:0.6169183087479904
Epoch:6, w1:0.954085383323548, w2:0.8068078189461868, bias:-0.5360750541438093, loss:0.6109217482457439
Epoch:7, w1:0.9609372736904126, w2:0.8017978336202497, bias:-0.5780656565280884, loss:0.6064328970399742
Epoch:8, w1:0.9696913132248329, w2:0.79995897835816, bias:-0.615119146283079, loss:0.6029722845978162
Epoch:9, w1:0.980005310172895, w2:0.8006849805266432, bi

(np.float64(9.364997046740006),
 np.float64(1.90989803946662),
 np.float64(-4.902768238473867))

In [72]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 1.0000 - loss: 0.3432


[0.3431582450866699, 1.0]

In [73]:
def gradient_descent(age, affordability, y_true, epochs, loss_threshold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)

        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_threshold:
            break
    return w1, w2, bias

In [74]:

gradient_descent(X_train_scaled['age'],X_train_scaled['affordability'],y_train,1000, 0.4230)

Epoch:0, w1:0.9795315209594441, w2:0.9492451509708789, bias:-0.11252165178733592, loss:0.7026974954757434
Epoch:1, w1:0.9645976725710581, w2:0.9075461514920868, bias:-0.2106906494479398, loss:0.6735456568147277
Epoch:2, w1:0.9547110050786667, w2:0.8742482165151655, bias:-0.29581941661734007, loss:0.6520372261076537
Epoch:3, w1:0.9492998511652697, w2:0.8484835924684363, bias:-0.3694132143012605, loss:0.6363983632285396
Epoch:4, w1:0.9477681190800475, w2:0.8292893292838077, bias:-0.4330203349934106, loss:0.6251004827815608
Epoch:5, w1:0.9495395977826652, w2:0.8156998101423668, bias:-0.48812360294921553, loss:0.6169183087479904
Epoch:6, w1:0.954085383323548, w2:0.8068078189461868, bias:-0.5360750541438093, loss:0.6109217482457439
Epoch:7, w1:0.9609372736904126, w2:0.8017978336202497, bias:-0.5780656565280884, loss:0.6064328970399742
Epoch:8, w1:0.9696913132248329, w2:0.79995897835816, bias:-0.615119146283079, loss:0.6029722845978162
Epoch:9, w1:0.980005310172895, w2:0.8006849805266432, bi

(np.float64(5.43262225693723),
 np.float64(1.5351265643538874),
 np.float64(-3.0844806386013395))

In [75]:
coef, intercept

(array([[5.4448314],
        [1.497577 ]], dtype=float32),
 array([-3.0453923], dtype=float32))

## write a class function

In [76]:
class myNN:
    def __init__(self):
        self.w1 = 1 
        self.w2 = 1
        self.bias = 0
        
    def fit(self, X, y, epochs, loss_thresold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'],X['affordibility'],y, epochs, loss_thresold)
        print(f"Final weights and bias: w1: {self.w1}, w2: {self.w2}, bias: {self.bias}")
        
    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordibility'] + self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age,affordability, y_true, epochs, loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordability + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)
            
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
            w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            
            if i%50==0:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            
            if loss<=loss_thresold:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break

        return w1, w2, bias

In [77]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=8000, loss_thresold=0.4230)

KeyError: 'affordibility'

In [ ]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=5, loss_thresold=0.4230)

KeyError: 'affordibility'

In [ ]:
customModel.predict(X_test_scaled)

In [ ]:
model.predict(X_test_scaled)